CREATE TABLE `task` (
                        `id` BIGINT NOT NULL COMMENT '主键ID',
                        `task_id` VARCHAR(64) NOT NULL COMMENT '任务ID（业务唯一标识）',
                        `message_id` VARCHAR(64) COMMENT 'RabbitMQ消息ID',
                        `task_type` VARCHAR(32) NOT NULL COMMENT '任务类型：EMAIL/SMS/CALC/REPORT/BACKUP',
                        `task_name` VARCHAR(128) COMMENT '任务名称',
                        `priority` TINYINT DEFAULT 5 COMMENT '优先级 1-10',
                        `status` TINYINT NOT NULL DEFAULT 0 COMMENT '状态：0-待处理，1-处理中，2-成功，3-失败，4-已取消，5-死信',
                        `current_stage` VARCHAR(32) COMMENT '当前阶段：PENDING/CONSUMING/PROCESSING/RETRYING',
                        `task_data` JSON COMMENT '任务数据（JSON格式）',
                        `task_result` JSON COMMENT '任务执行结果（JSON格式）',
                        `error_msg` VARCHAR(2000) COMMENT '错误信息',
                        `retry_count` INT DEFAULT 0 COMMENT '已重试次数',
                        `max_retry` INT DEFAULT 3 COMMENT '最大重试次数',
                        `delay_ms` BIGINT DEFAULT 0 COMMENT '延迟毫秒数',
                        `execute_time` DATETIME COMMENT '计划执行时间（延迟任务）',
                        `start_time` DATETIME COMMENT '开始执行时间',
                        `finish_time` DATETIME COMMENT '完成时间',
                        `duration_ms` BIGINT COMMENT '执行耗时（毫秒）',
                        `queue_name` VARCHAR(128) COMMENT '队列名称',
                        `exchange_name` VARCHAR(128) COMMENT '交换机名称',
                        `routing_key` VARCHAR(128) COMMENT '路由键',
                        `trace_id` VARCHAR(64) COMMENT '链路追踪ID',
                        `batch_id` VARCHAR(64) COMMENT '批次ID（批量提交时）',
                        `create_user` BIGINT COMMENT '创建人ID',
                        `create_user_name` VARCHAR(64) COMMENT '创建人名称',
                        `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                        `update_user` BIGINT COMMENT '更新人ID',
                        `update_user_name` VARCHAR(64) COMMENT '更新人名称',
                        `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
                        `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0-正常，1-已删除',
                        PRIMARY KEY (`id`),
                        UNIQUE KEY `uk_task_id` (`task_id`),
                        KEY `idx_status` (`status`),
                        KEY `idx_task_type` (`task_type`),
                        KEY `idx_create_time` (`create_time`),
                        KEY `idx_batch_id` (`batch_id`),
                        KEY `idx_trace_id` (`trace_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='任务表';


CREATE TABLE `task_execution_log` (
                                      `id` BIGINT NOT NULL COMMENT '主键ID',
                                      `task_id` VARCHAR(64) NOT NULL COMMENT '任务ID',
                                      `execution_no` INT NOT NULL COMMENT '执行次数（第几次执行）',
                                      `status` TINYINT NOT NULL COMMENT '执行状态：0-开始，1-成功，2-失败',
                                      `start_time` DATETIME NOT NULL COMMENT '开始时间',
                                      `end_time` DATETIME COMMENT '结束时间',
                                      `duration_ms` BIGINT COMMENT '执行耗时（毫秒）',
                                      `input_data` JSON COMMENT '输入数据',
                                      `output_data` JSON COMMENT '输出数据',
                                      `error_msg` VARCHAR(2000) COMMENT '错误信息',
                                      `stack_trace` TEXT COMMENT '异常堆栈',
                                      `consumer_tag` VARCHAR(64) COMMENT '消费者标签',
                                      `queue_name` VARCHAR(128) COMMENT '队列名称',
                                      `create_user` BIGINT COMMENT '创建人ID',
                                      `create_user_name` VARCHAR(64) COMMENT '创建人名称',
                                      `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                                      `update_user` BIGINT COMMENT '更新人ID',
                                      `update_user_name` VARCHAR(64) COMMENT '更新人名称',
                                      `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
                                      `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0-正常，1-已删除',
                                      PRIMARY KEY (`id`),
                                      KEY `idx_task_id` (`task_id`),
                                      KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='任务执行日志表';


CREATE TABLE `dead_letter_message` (
                                       `id` BIGINT NOT NULL COMMENT '主键ID',
                                       `message_id` VARCHAR(64) NOT NULL COMMENT '消息ID',
                                       `task_id` VARCHAR(64) COMMENT '关联的任务ID',
                                       `task_type` VARCHAR(32) COMMENT '任务类型',
                                       `original_queue` VARCHAR(128) NOT NULL COMMENT '原队列名称',
                                       `original_exchange` VARCHAR(128) COMMENT '原交换机',
                                       `original_routing_key` VARCHAR(128) COMMENT '原路由键',
                                       `message_body` JSON NOT NULL COMMENT '消息体内容',
                                       `death_reason` VARCHAR(64) NOT NULL COMMENT '死亡原因：REJECTED/EXPIRED/DELIVERY_LIMIT',
                                       `death_count` INT DEFAULT 1 COMMENT '死亡次数',
                                       `death_time` DATETIME NOT NULL COMMENT '进入死信队列时间',
                                       `error_msg` VARCHAR(2000) COMMENT '错误信息',
                                       `stack_trace` TEXT COMMENT '异常堆栈',
                                       `x_death_info` JSON COMMENT 'x-death完整信息',
                                       `retry_status` TINYINT DEFAULT 0 COMMENT '重试状态：0-未重试，1-已重试，2-重试成功，3-重试失败',
                                       `retry_time` DATETIME COMMENT '最后重试时间',
                                       `retry_count` INT DEFAULT 0 COMMENT '重试次数',
                                       `create_user` BIGINT COMMENT '创建人ID',
                                       `create_user_name` VARCHAR(64) COMMENT '创建人名称',
                                       `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                                       `update_user` BIGINT COMMENT '更新人ID',
                                       `update_user_name` VARCHAR(64) COMMENT '更新人名称',
                                       `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
                                       `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0-正常，1-已删除',
                                       PRIMARY KEY (`id`),
                                       UNIQUE KEY `uk_message_id` (`message_id`),
                                       KEY `idx_task_id` (`task_id`),
                                       KEY `idx_retry_status` (`retry_status`),
                                       KEY `idx_death_time` (`death_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='死信消息表';


CREATE TABLE `message_idempotent` (
                                      `id` BIGINT NOT NULL COMMENT '主键ID',
                                      `message_id` VARCHAR(64) NOT NULL COMMENT '消息ID',
                                      `task_id` VARCHAR(64) COMMENT '任务ID',
                                      `consumer_name` VARCHAR(128) NOT NULL COMMENT '消费者名称',
                                      `status` TINYINT NOT NULL DEFAULT 0 COMMENT '处理状态：0-处理中，1-已处理，2-处理失败',
                                      `process_time` DATETIME COMMENT '处理时间',
                                      `expire_time` DATETIME NOT NULL COMMENT '过期时间（用于清理）',
                                      `create_user` BIGINT COMMENT '创建人ID',
                                      `create_user_name` VARCHAR(64) COMMENT '创建人名称',
                                      `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                                      `update_user` BIGINT COMMENT '更新人ID',
                                      `update_user_name` VARCHAR(64) COMMENT '更新人名称',
                                      `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
                                      `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0-正常，1-已删除',
                                      PRIMARY KEY (`id`),
                                      UNIQUE KEY `uk_message_id_consumer` (`message_id`, `consumer_name`),
                                      KEY `idx_expire_time` (`expire_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='消息幂等记录表';

CREATE TABLE `queue_monitor_history` (
                                         `id` BIGINT NOT NULL COMMENT '主键ID',
                                         `queue_name` VARCHAR(128) NOT NULL COMMENT '队列名称',
                                         `vhost` VARCHAR(64) DEFAULT '/' COMMENT '虚拟主机',
                                         `messages_ready` INT DEFAULT 0 COMMENT '待消费消息数',
                                         `messages_unacknowledged` INT DEFAULT 0 COMMENT '未确认消息数',
                                         `messages_total` INT DEFAULT 0 COMMENT '总消息数',
                                         `consumers` INT DEFAULT 0 COMMENT '消费者数量',
                                         `publish_rate` DECIMAL(10,2) DEFAULT 0 COMMENT '发布速率（条/秒）',
                                         `deliver_rate` DECIMAL(10,2) DEFAULT 0 COMMENT '消费速率（条/秒）',
                                         `ack_rate` DECIMAL(10,2) DEFAULT 0 COMMENT '确认速率（条/秒）',
                                         `memory_used` BIGINT DEFAULT 0 COMMENT '内存使用（字节）',
                                         `create_user` BIGINT COMMENT '创建人ID',
                                         `create_user_name` VARCHAR(64) COMMENT '创建人名称',
                                         `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                                         `update_user` BIGINT COMMENT '更新人ID',
                                         `update_user_name` VARCHAR(64) COMMENT '更新人名称',
                                         `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
                                         `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0-正常，1-已删除',
                                         PRIMARY KEY (`id`),
                                         KEY `idx_queue_name` (`queue_name`),
                                         KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='队列监控历史表';

CREATE TABLE `task_config` (
                               `id` BIGINT NOT NULL COMMENT '主键ID',
                               `task_type` VARCHAR(32) NOT NULL COMMENT '任务类型',
                               `task_type_name` VARCHAR(64) NOT NULL COMMENT '任务类型名称',
                               `default_priority` TINYINT DEFAULT 5 COMMENT '默认优先级',
                               `default_max_retry` INT DEFAULT 3 COMMENT '默认最大重试次数',
                               `default_timeout` INT DEFAULT 30000 COMMENT '默认超时时间（毫秒）',
                               `queue_name` VARCHAR(128) NOT NULL COMMENT '队列名称',
                               `exchange_name` VARCHAR(128) NOT NULL COMMENT '交换机名称',
                               `routing_key` VARCHAR(128) NOT NULL COMMENT '路由键',
                               `dlq_queue_name` VARCHAR(128) COMMENT '死信队列名称',
                               `dlq_exchange_name` VARCHAR(128) COMMENT '死信交换机名称',
                               `enabled` TINYINT DEFAULT 1 COMMENT '是否启用：0-禁用，1-启用',
                               `description` VARCHAR(256) COMMENT '描述',
                               `create_user` BIGINT COMMENT '创建人ID',
                               `create_user_name` VARCHAR(64) COMMENT '创建人名称',
                               `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                               `update_user` BIGINT COMMENT '更新人ID',
                               `update_user_name` VARCHAR(64) COMMENT '更新人名称',
                               `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
                               `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0-正常，1-已删除',
                               PRIMARY KEY (`id`),
                               UNIQUE KEY `uk_task_type` (`task_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='任务配置表';